{{- if .Values.secrets.enabled }}
{{- if and .Values.sealedSecrets.enabled .Values.sealedSecrets.encryptedData }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "capsule-brain.fullname" . }}-env
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
{{- toYaml .Values.sealedSecrets.encryptedData | nindent 4 }}
  template:
    metadata:
      name: {{ include "capsule-brain.fullname" . }}-env
    type: Opaque
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "capsule-brain.fullname" . }}-env
type: Opaque
stringData:
{{- toYaml .Values.secrets.stringData | nindent 2 }}
{{- end }}
{{- end }}
